#!/usr/bin/env python3
"""
Executive summary generator for SFWeather.

Produces ``data/executive_summary.md`` (a printable, shareable document) and
``data/executive_summary.json`` (its structured mirror) from the already-
verified datasets this project commits: ``landlord.json``, ``cpc.json``,
``run.json``, ``calendar.json``, ``nws.json``.

Design rule, same as the rest of the pipeline: **no number is invented here.**
Every figure in the output is copied verbatim from a field of the input
datasets, and every link is copied from a URL those datasets already carry.
The prose that frames them contains no figures of its own.  That is the
countermeasure to the bug-40 lesson (a hand-typed table in prose contradicted
the dataset within weeks): a document a human retypes will drift; a document
the pipeline regenerates nightly cannot.

Offline: standard library only.  Reads whatever ``SFWEATHER_DATA`` points at
(the falsification harness relies on that), defaults to ``data/``.

Exit codes: 0 = document written; 1 = a required input dataset is missing or
empty (loud failure: publishing without a summary is better than publishing a
half-built one, and the publish gate treats a non-zero exit as "do not ship").
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
_env = os.environ.get("SFWEATHER_DATA")
if _env:
    DATA = Path(_env)

OUT_MD = DATA / "executive_summary.md"
OUT_JSON = DATA / "executive_summary.json"

REQUIRED = ("landlord.json", "run.json")


def load(name):
    p = DATA / name
    if not p.exists():
        return {}
    try:
        return json.loads(p.read_text())
    except json.JSONDecodeError:
        return {}


def esc(text):
    """Markdown-escape the two characters that would break a table cell."""
    return str(text).replace("|", "\\|").replace("\n", " ")


def fmt_numbers(numbers):
    """Render a bottom-line number block as a markdown table."""
    lines = ["| Figure | Value |", "| --- | --- |"]
    for n in numbers or []:
        lines.append(f"| {esc(n.get('label') or 'figure')} | {esc(n.get('value') or 'not published')} |")
    return "\n".join(lines)


def fmt_sources(sources):
    out = []
    for s in sources or []:
        label = s.get("label") or "source"
        url = s.get("url") or ""
        out.append(f"[{esc(label)}]({url})" if url else esc(label))
    return "; ".join(out) if out else "_no source link recorded — this item would be withheld on the site_"


def build_markdown():
    """Assemble the document.  Returns (markdown_text, structured_dict)."""
    landlord = load("landlord.json")
    run = load("run.json")
    cpc = load("cpc.json")
    calendar = load("calendar.json")
    nws = load("nws.json")

    missing = [n for n in REQUIRED if not load(n)]
    if missing:
        raise SystemExit(f"executive_summary: required dataset(s) missing or empty: {', '.join(missing)}")

    es = landlord.get("executive_summary") or {}
    if not es.get("bottom_line") or not es.get("cost_drivers"):
        raise SystemExit("executive_summary: landlord.json lacks bottom_line or cost_drivers; refusing to build")

    generated = landlord.get("generated_utc") or run.get("generated_utc") or "unknown"
    target = (run.get("target") or {})
    window = es.get("season_window") or "the Oct 1 - Jan 31 season"
    location = es.get("location") or target.get("label") or "San Francisco, CA 94122"
    coord_src = es.get("verified_coordinate_source") or ""
    coord_url = es.get("coordinate_source_url") or ""

    md = []
    md.append("# Executive summary — weather-driven repair & maintenance risk, ZIP 94122")
    md.append("")
    md.append(f"**{esc(location)}** · Season window: **{esc(window)}** · "
              f"Generated by the SFWeather pipeline at **{esc(generated)}** (UTC).")
    md.append("")
    md.append("> **How to read this document.** Every figure below is either an observed "
              "1991–2020 statistic from an official NOAA station or an official CPC/NWS "
              "probability, and each carries the link to its source so a reviewer can check "
              "it line by line. No official product forecasts a named day beyond the current "
              "NWS horizon; where this document speaks about the season it speaks in observed "
              "statistics and official period probabilities, never in invented daily values. "
              "The repair-and-maintenance framing is guidance, not a weather claim.")
    md.append("")

    # ------------------------------------------------- Outer Sunset profile
    osp = es.get("outer_sunset_profile") or {}
    if osp:
        md.append("## Outer Sunset SF 94122 Property & Weather Profile")
        md.append("")
        for k, label in (
            ("neighborhood", "Neighborhood"),
            ("centroid_coordinates", "Centroid & Location"),
            ("ocean_exposure", "Pacific Ocean Exposure"),
            ("building_stock_vulnerabilities", "Building Typology & Vulnerabilities"),
            ("soil_and_drainage", "Subsoil & Urban Drainage"),
            ("marine_corrosion", "Salt-Air Marine Environment"),
        ):
            if osp.get(k):
                md.append(f"- **{label}:** {esc(osp[k])}")
        md.append("")

    # ------------------------------------------------- the six questions
    md.append("## 1. The landlord's six questions, answered from the record")
    md.append("")
    if es.get("bottom_line_note"):
        md.append(f"_{esc(es['bottom_line_note'])}_")
        md.append("")
    for item in es.get("bottom_line") or []:
        md.append(f"### Q{item.get('n')}: {esc(item.get('question'))}")
        md.append("")
        md.append(esc(item.get("answer") or "_no answer published_"))
        md.append("")
        if item.get("numbers"):
            md.append(fmt_numbers(item["numbers"]))
            md.append("")
        basis_bits = []
        if item.get("basis"):
            basis_bits.append(f"**Basis:** {esc(item['basis'])}")
        if item.get("confidence"):
            basis_bits.append(f"**Confidence:** {esc(item['confidence'])}")
        if basis_bits:
            md.append(" · ".join(basis_bits))
            md.append("")
        md.append(f"**Verify:** {fmt_sources(item.get('sources'))}")
        md.append("")

    # ------------------------------------------------- official outlook
    outlook = es.get("official_outlook") or {}
    md.append("## 2. The official outlook right now")
    md.append("")
    enso = outlook.get("enso") or {}
    if enso:
        md.append(f"- **ENSO state:** {esc(enso.get('state') or 'not published')}"
                  + (f" — alert status: {esc(enso.get('alert_status'))}" if enso.get("alert_status") else ""))
        if enso.get("source_url"):
            md.append(f"  - Verify: [{esc(enso['source_url'])}]({enso['source_url']})")
    estr = outlook.get("enso_strength") or {}
    if estr.get("available") and estr.get("quotes"):
        md.append("- **How strong CPC expects this El Niño to get (quoted verbatim):**")
        for q in estr["quotes"]:
            md.append(f"  - {esc(q.get('label') or q.get('key'))}: “{esc(q.get('text'))}”")
        if estr.get("source_url"):
            md.append(f"  - Verify the whole discussion: [{esc(estr['source_url'])}]({estr['source_url']})")
    elif estr.get("available") is False:
        md.append("- **El Niño strength outlook:** not available this run — "
                  + esc(estr.get("reason") or "see the outlook strip on the site"))
    tilt = outlook.get("cpc_tilt") or {}
    if tilt:
        md.append(f"- **CPC long-lead outlooks:** {esc(tilt.get('periods_covering_this_season'))} "
                  f"period(s) cover this season; {esc(tilt.get('periods_with_a_tilt'))} carry a tilt away "
                  f"from the one-in-three climatological baseline, "
                  f"{esc(tilt.get('periods_at_climatological_baseline'))} sit at the baseline (Equal Chances).")
        hp = tilt.get("highest_probability") or {}
        if hp:
            md.append(f"  - Strongest tilt: **{esc(hp.get('period'))} — {esc(hp.get('category_label'))} "
                      f"at {esc(hp.get('probability_pct'))}%** (issued {esc(hp.get('issued'))}).")
            if hp.get("source_url"):
                md.append(f"  - Verify: [{esc(hp['source_url'])}]({hp['source_url']})")
        for row in tilt.get("rows") or []:
            md.append(f"  - {esc(row.get('period'))}: {esc(row.get('category_label'))} "
                      f"({esc(row.get('probability_pct'))}%), issued {esc(row.get('issued'))}.")
    cav = outlook.get("prognostic_caveats") or {}
    if cav.get("available") and cav.get("quotes"):
        md.append("- **What NOAA's own forecasters caution about this outlook (quoted verbatim):**")
        for q in cav["quotes"]:
            md.append(f"  - {esc(q.get('label') or q.get('key'))}: “{esc(q.get('text'))}”")
        if cav.get("source_url"):
            md.append(f"  - Verify the whole discussion: [{esc(cav['source_url'])}]({cav['source_url']})")
    elif cav.get("available") is False:
        md.append("- **Outlook caveats:** not available this run — "
                  + esc(cav.get("reason") or "see the caveats card on the site"))
    ecr = outlook.get("enso_conditioned_record") or {}
    if ecr and ecr.get("mean_in") is not None:
        md.append(f"- **The observed record in seasons like this one ({esc(ecr.get('phase_label'))}, "
                  f"n = {esc(ecr.get('seasons_in_phase'))} seasons):** mean {esc(ecr.get('mean_in'))} in, "
                  f"median {esc(ecr.get('median_in'))} in, range {esc(ecr.get('min_in'))}–"
                  f"{esc(ecr.get('max_in'))} in. {esc(ecr.get('how_to_read') or '')}")
        for c in ecr.get("contrast") or []:
            md.append(f"  - Contrast: {esc(c.get('phase_label'))} seasons (n = {esc(c.get('seasons'))}) "
                      f"averaged {esc(c.get('mean_in'))} in.")
        if ecr.get("source_url"):
            md.append(f"  - Verify: [{esc(ecr['source_url'])}]({ecr['source_url']})")
    # The severity counters (hard-rain days, gusts, wind + rain) in the seasons
    # that sat in this same phase, beside all 30.  Copied row by row from the
    # dataset; the phase, its n and the all-season figure are printed in every
    # row because a small-sample conditional average must never be read as a
    # settled number, let alone a forecast.
    ecs = outlook.get("enso_conditioned_severity") or {}
    if ecs and ecs.get("rows"):
        md.append("")
        md.append(f"**Hard rain, wind and wind + rain in past {esc(ecs.get('phase_label'))} seasons "
                  f"(n = {esc(ecs.get('seasons_in_phase'))} of {esc(ecs.get('seasons_total'))}), "
                  "beside all seasons:**")
        md.append("")
        md.append(f"| Counter (per Oct 1 – Jan 31 season) | {esc(ecs.get('phase_label'))} seasons "
                  f"(n = {esc(ecs.get('seasons_in_phase'))}): mean · median · max | "
                  f"All {esc(ecs.get('seasons_total'))} seasons: mean · max |")
        md.append("| --- | --- | --- |")
        for r in ecs["rows"]:
            md.append(f"| {esc(r.get('label'))} | {esc(r.get('phase_mean'))} · "
                      f"{esc(r.get('phase_median'))} · {esc(r.get('phase_max'))} | "
                      f"{esc(r.get('all_mean'))} · {esc(r.get('all_max'))} |")
        md.append("")
        if ecs.get("how_to_read"):
            md.append(f"_{esc(ecs['how_to_read'])}_")
            md.append("")
        if ecs.get("sources"):
            md.append(f"Verify: {fmt_sources(ecs['sources'])}")
            md.append("")
    daily = outlook.get("daily_forecast") or {}
    if daily and daily.get("official_horizon_ends"):
        md.append(f"- **The live NWS forecast:** {esc(daily.get('days_in_this_scoreboard_with_a_real_forecast'))} "
                  f"scoreboard day(s) currently carry a real daily forecast; the official horizon ends "
                  f"{esc(daily['official_horizon_ends'])}.")
    md.append("")

    # ------------------------------------------------- cost drivers
    md.append("## 3. Repair & maintenance cost drivers — ranked")
    md.append("")
    if es.get("cost_drivers_note"):
        md.append(f"_{esc(es['cost_drivers_note'])}_")
        md.append("")
    for d in sorted(es.get("cost_drivers") or [], key=lambda x: x.get("rank") or 0):
        md.append(f"### Rank {d.get('rank')}: {esc(d.get('driver'))}")
        md.append("")
        if d.get("why_it_costs"):
            md.append(f"**Why it costs (guidance, not a weather claim):** {esc(d['why_it_costs'])}")
            md.append("")
        if d.get("evidence"):
            md.append("| Evidence | Value |")
            md.append("| --- | --- |")
            for e in d["evidence"]:
                md.append(f"| {esc(e.get('label'))} | {esc(e.get('value'))} |")
            md.append("")
        md.append(f"**Verify:** {fmt_sources(d.get('sources'))}")
        md.append("")

    # ------------------------------------------------- expected counts + severity
    exp = es.get("expected_days") or {}
    sev = es.get("severity") or {}

    def threshold_from_key(key):
        # wet_days_ge_050in -> "0.50", ge_025in_days -> "0.25",
        # wet_days_ge_1in -> "1.00": the threshold text is derived from the
        # dataset's own key, never typed in prose.
        import re as _re
        m = _re.search(r"ge[_]?(\d{1,3})in", key)
        if not m:
            return None
        d = m.group(1)
        if len(d) == 3:
            return f"{d[0]}.{d[1:]}"
        return f"{d}.00"

    if exp or sev:
        md.append("## 4. Expected day counts and severe-rain frequency")
        md.append("")
        for key in ("ge_025in_days", "ge_100in_days"):
            if exp.get(key) is not None:
                thr = threshold_from_key(key)
                method = str(exp.get("method") or "see methods").rstrip(".")
                md.append(f"- Expected days with at least {thr} in of rain this season window: "
                          f"**{esc(exp[key])}** — {esc(method)}.")
        for key in sorted(sev.keys()):
            s = sev.get(key) or {}
            thr = threshold_from_key(key)
            if thr and s.get("mean") is not None:
                md.append(f"- Seasons carry on average **{esc(s['mean'])}** days with at least {thr} in "
                          f"(median {esc(s.get('median'))}, worst season {esc(s.get('max'))}, "
                          f"n = {esc(s.get('n'))} seasons).")
        md.append("")

    # ------------------------------------------------ the ocean-side wind record
    # SFO is on the bay shore.  This is the nearest official anemometer on the
    # ocean side, published with the buoy dataset's own caveat; every figure is
    # copied from that dataset and the ledger re-derives them.
    ows = es.get("ocean_wind") or {}
    if ows.get("available"):
        md.append("## 4b. The ocean side of the wind question — NOAA NDBC buoy "
                  f"{esc(ows.get('station_id'))}")
        md.append("")
        md.append("Every other wind figure in this document is measured at SFO, on the bay "
                  "shore. This is the nearest official anemometer on the ocean side of the "
                  "Golden Gate, so the ocean side of the question has numbers of its own.")
        md.append("")
        md.append(f"- **Station:** {esc(ows.get('station_id'))} — {esc(ows.get('station_name'))} "
                  f"({esc(ows.get('station_type'))})")
        md.append(f"- **Position:** {esc(ows.get('position', {}).get('lat'))} N, "
                  f"{esc(ows.get('position', {}).get('lon'))} W · "
                  f"**{esc(ows.get('distance_mi_from_centroid'))} mi** from the 94122 centroid · "
                  f"anemometer {esc(ows.get('anemometer_height_m'))} m above the sea surface · "
                  f"mooring depth {esc(ows.get('water_depth_m'))} m")
        md.append(f"- **Record:** {esc(ows.get('window_label'))} · day basis: "
                  f"{esc(ows.get('day_basis'))} · seasons with data: "
                  f"{esc(ows.get('seasons_with_data'))} of {esc(ows.get('seasons_total'))}")
        gale = ows.get("gale_days_ge_34kt") or {}
        d40 = ows.get("days_ge_40kt") or {}
        sfo40 = ows.get("sfo_days_ge_40kt") or {}
        gust = ows.get("max_gust_mph") or {}
        wave = ows.get("max_wvht_ft") or {}
        md.append(f"- **Gale-force gust days (≥ 34 kt) per season:** mean {esc(gale.get('mean'))} · "
                  f"median {esc(gale.get('median'))} · worst season {esc(gale.get('max'))} "
                  f"(n = {esc(gale.get('n_seasons'))} seasons)")
        md.append(f"- **At the same 40 kt gust threshold as the SFO table:** the buoy averages "
                  f"{esc(d40.get('mean'))} days per season (max {esc(d40.get('max'))}) against "
                  f"SFO's {esc(sfo40.get('mean'))}. Two different environments — open water and "
                  "a bay-shore airport — and neither is a bound for a street in the Sunset.")
        md.append(f"- **Strongest gust of the season:** mean {esc(gust.get('mean'))} mph · worst "
                  f"season {esc(gust.get('max'))} mph. **Highest significant wave height:** mean "
                  f"{esc(wave.get('mean'))} ft · worst season {esc(wave.get('max'))} ft")
        if ows.get("thin_seasons"):
            md.append(f"- **Seasons thinner than the published cut:** "
                      f"{esc(', '.join(ows['thin_seasons'][:10]))}")
        if ows.get("counter_basis"):
            md.append(f"- _{esc(ows.get('counter_basis'))}_")
        md.append("")
        md.append(f"**Marine caveat, as published with the data:** {esc(ows.get('caveat'))}")
        md.append("")
    elif ows:
        md.append("## 4b. The ocean side of the wind question — not in this snapshot")
        md.append("")
        md.append(f"_{esc(ows.get('reason'))}_")
        md.append("")

    # ------------------------------------------------- what cannot be known
    md.append("## 5. What this document cannot tell you")
    md.append("")
    md.append("No official product — NOAA, NWS, CPC or any national agency — forecasts a named "
              "day beyond the current NWS forecast horizon, which the pipeline reads from the "
              "fetched product on every run. Beyond that window this project publishes the "
              "1991–2020 observed record for each calendar date and official period "
              "probabilities; it never invents a daily forecast. Daily forecast values fill in "
              "automatically on this site as the season approaches and each day enters the NWS "
              "window.")
    md.append("")
    win = calendar.get("nws_window") or {}
    if win.get("first_day") and win.get("last_day"):
        md.append(f"At generation time the official NWS window covered {esc(win['first_day'])} "
                  f"through {esc(win['last_day'])} ({esc(win.get('horizon_days'))} days); "
                  f"{esc(win.get('scoreboard_days_in_horizon'))} of the season's scoreboard days "
                  "were inside it. Verify:")
        for key, label in (("daily_url", "daily forecast"), ("hourly_url", "hourly forecast"),
                           ("human_url", "human-readable forecast")):
            if win.get(key):
                md.append(f"- {label}: [{esc(win[key])}]({win[key]})")
        md.append("")

    # ------------------------------------------------- manual review links
    md.append("## 6. Verify everything yourself — official links")
    md.append("")
    links = []
    pt = (nws.get("point") or {})
    if pt.get("forecast_office"):
        links.append(("NWS forecast office for this point", pt["forecast_office"]))
    if pt.get("forecast_zone"):
        links.append(("NWS forecast zone for this point (CAZ006)", pt["forecast_zone"]))
    if win.get("human_url"):
        links.append(("NWS human-readable forecast", win["human_url"]))
    if coord_url:
        links.append((f"ZIP centroid ({esc(coord_src)})" if coord_src else "ZIP centroid", coord_url))
    ghcn = "https://www.ncei.noaa.gov/data/global-historical-climatology-network-daily/access/USW00023272.csv"
    links.append(("NCEI GHCN-Daily USW00023272 (SF downtown gauge, 1991–2020 basis)", ghcn))
    if enso.get("source_url"):
        links.append(("CPC ENSO diagnostic discussion", enso["source_url"]))
    if cav.get("source_url"):
        links.append(("CPC long-lead prognostic discussion (caveats quoted above)", cav["source_url"]))
    if ows.get("available"):
        srcs = ows.get("source_urls") or {}
        if srcs.get("station_page"):
            links.append(("NDBC buoy 46026 — station page (sensor heights, latest observations)",
                          srcs["station_page"]))
        if srcs.get("units"):
            links.append(("NDBC — Measurement Descriptions and Units (the units quoted above)",
                          srcs["units"]))
    seen = set()
    for label, url in links:
        if url in seen:
            continue
        seen.add(url)
        md.append(f"- {label}: [{esc(url)}]({url})")
    md.append("")

    md.append("---")
    md.append("")
    md.append(f"_{esc(landlord.get('disclaimer') or '')}_")
    if landlord.get("verification_note"):
        md.append("")
        md.append(f"_{esc(landlord['verification_note'])}_")
    md.append("")

    structured = {
        "generated_utc": generated,
        "location": location,
        "season_window": window,
        "outer_sunset_profile": osp,
        "questions": es.get("bottom_line"),
        "cost_drivers": es.get("cost_drivers"),
        "ocean_wind": es.get("ocean_wind"),
        "official_outlook": outlook,
        "inputs": sorted(REQUIRED) + ["calendar.json", "cpc.json", "nws.json"],
        "note": "Machine-generated from the committed datasets on every pipeline run. "
                "Hand edits will be overwritten and are detected by the claim ledger.",
    }
    return "\n".join(md) + "\n", structured


def main():
    md, structured = build_markdown()
    OUT_MD.write_text(md, encoding="utf-8")
    OUT_JSON.write_text(json.dumps(structured, indent=2), encoding="utf-8")
    print(f"executive summary: wrote {OUT_MD} ({len(md)} chars) and {OUT_JSON}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
